### ISSUE TITLE
Issue with smb2_set_seal() and connecting to servers enforcing encryption

### ISSUE THREAD

**Issue by tguillem** [sahlberg/libsmb2#174] opened 2020-11-13 15:56 UTC
I have trouble connecting to samba Version 4.9.5-Debian (likely the same issue with more recent servers) with the following conf:

```
[global]
	encrypt passwords = true
	min protocol = SMB2
	max protocol = SMB3
	server signing = mandatory
	smb encrypt = mandatory
```

I receive a SMB2_STATUS_ACCESS_DENIED if I don't enable seal with smb2_set_seal(smb2, 1);

But I have 2 problems with this function:

- I don't want to fail if the server doesn't support encryption, cf. `smb2_set_error(smb2, "Encryption requested but server does not support encryption.");`. Should we differentiate REQUIRED vs ENABLED?
- I got a read error from `smb2_service` after few read requests when seal is enabled. `readv` is returning 0 from `smb2_read_data`, this cause the following error path /* remote side has closed the socket. */.

I'm using libsmb2 from master with NTLM.

**Comment by sahlberg** [comment] 2020-11-13 17:23
On Sat, Nov 14, 2020 at 1:56 AM Thomas Guillem <notifications@github.com>
wrote:

> I have trouble connecting to samba Version 4.9.5-Debian (likely the same
> issue with more recent servers) with the following conf:
>
> [global]
> 	encrypt passwords = true
> 	min protocol = SMB2
> 	max protocol = SMB3
> 	server signing = mandatory
> 	smb encrypt = mandatory
>
>
Interesting. Samba allows you to set both signing and seal as mandatory.
SMB2 suggests that when encryption is used signing should not be used. But
it works, so...

 I receive a SMB2_STATUS_ACCESS_DENIED if I don't enable seal with
> smb2_set_seal(smb2, 1);
>
> But I have 2 problems with this function:
>
>    - I don't want to fail if the server doesn't support encryption, cf. smb2_set_error(smb2,
>    "Encryption requested but server does not support encryption.");.
>    Should we differentiate REQUIRED vs ENABLED?
>
> Yes, we need to do something here. While we know from the server whether
signing is required or not there is no such hint from the server as whether
seal is required or not.

I think what we need to do here for the default case is to first try to
login with seal==0 and if that fails fallback to try with seal==1
That way we will work with servers that require encryption but only use
encryption IFF the servers require it.

So this means
smb2_set_seal(smb2, 0),  which is the default, will become: use encryption
if the server requres it, otherwise not

and
smb2_set_seal(smb2, 1) remains : session must be encrypted or fail.

I will work on implementing this tomorrow.

**Comment by sahlberg** [comment] 2020-11-13 18:24
Please try current master.

**Comment by tguillem** [comment] 2020-11-16 13:30
Thanks @sahlberg it fixes my first issue. Seal is now enabled automatically.

I still have another issue: with your last patches or by forcing seal, readv() returns 0 after few requests (~100 - 200 readv calls).

I still could not figure if the problem is from VLC, libsmb2 or from my server (no problems with other clients)

**Comment by sahlberg** [comment] 2020-11-17 08:01
On Mon, Nov 16, 2020 at 11:30 PM Thomas Guillem <notifications@github.com>
wrote:

> Thanks @sahlberg <https://github.com/sahlberg> it fixes my first issue.
> Seal is now enabled automatically.
>
> I still have another issue: with your last patches or by forcing seal,
> readv() returns 0 after few requests (~100 - 200 readv calls).
>
> I still could not figure if the problem is from VLC, libsmb2 or from my
> server (no problems with other clients)
>
Hm. Does this only happen when you have seal enabled?
Do you have a network trace? I know I can't see the content of the traffic,
but it would give me an idea of PDU sizes
and also if there is a TCP layer disconnect or similar (which I don't do
reconnect for yet).

I will look into this on saturday.

Do you have an idea of what kind of operations that are issued to the
server?
I assume it is mainly open a file then sequentially read large blocks
sequentially ?


regards
ronnie sahlberg

**Comment by tguillem** [comment] 2020-11-17 09:21
It happens when I force encryption with smb2_set_seal(smb2,1) on the server where "smb encrypt" is default.

It happens when reading large blocks of a file. Not sure it doesn't happen when listing files/shares.
It is systematic but doesn't fail at the same point every time. Sometimes, I can read enough to get the first seconds of a SD video, sometimes, no video at all.

I will try with a newer version of samba, and will try to get some tcp dumps.

**Comment by tguillem** [comment] 2020-11-17 14:11
Here is the wireshark dump:

[smb3-encryption-readv0.pcapng.zip](https://github.com/sahlberg/libsmb2/files/5553930/smb3-encryption-readv0.pcapng.zip)

It happens also on a newer Samba Version 4.12.5-Debian

**Comment by sahlberg** [comment] 2020-11-23 07:23
Hi,

Can you try current master?

In the trace you sent me, packet 433 got me in the right direction.
It is an encrypted packet from the server but the encrypted PDU is only 73
bytes.
That is too small for a normal PDU so it had to be an error PDU.
It was a error PDU with STATUS_PENDING which is just a hint from the server
that
it has received the request proper but it may take a while to process and
respond.

Samba sends STATUS_PENDING via its async layer when it thinks that a read
might take longish.
As far as I know, Windows never issue these "errors" yet?  Am I correct you
only see this failure with Samba, not Windows?

Anyway, STATUS_PENDING needs special handling in smb2_read_data() and be
ignored since we will receive another full
response later.
The bug here was that in the special handling of STATUS_PENDING I set the
expected total of this blob to include the 4 byte
SPL header, but this header is only there when we are reading and
processing straight of the tcp socket and is not present in the decrypted
memory buffer we get after the decryption.

Thanks for this, and sorry for the bug.

**Comment by tguillem** [comment] 2020-11-23 11:21
Hello,

Current master fixes the issue I reported, thanks!

Unfortunately, I encountered a new issue with encryption (still when seal is forced on client or server) when testing another sample (a bigger one).

Here is the error: "Failed to decrypt PDU" from smb3-seal.c

and the dump: [smb-encrypt-failed-pdu.zip](https://github.com/sahlberg/libsmb2/files/5582537/smb-encrypt-failed-pdu.zip)

**Comment by delins** [comment] 2021-01-29 22:24
If I'm not mistaken, in your dump it seems a session is being set up while another session is still transferring data. Are you using the library from multiple threads, by any chance?

**Comment by tguillem** [comment] 2021-02-01 13:13
@delins From VLC, one smb2_context is used by a single thread, but there can be different smb2 access opened in // (preparsing, playback, medialibrary).

I can't reproduce this issue anymore (with or without your latest commits). Could this issue be linked with #183 by any chance ?

**Comment by delins** [comment] 2021-02-01 14:51
Could be. Even before the latest commits, as long as only one thread was accessing the encryption/decryption code at a time there were no race conditions afaik (the globals in the aes code needed to be stable during the invocation of the enc/dec functions, after that another thread could freely modify them). So perhaps your threads are simply not doing any encryption work concurrently now. Are you sure you still have sealing turned on while trying to reproduce it? :)

**Comment by tguillem** [comment] 2021-02-01 15:34
I'm not testing it on the same PC / local network. I will try tomorrow since it's my office day of the week.

Yes, I'm sure that seal is turned on.

**Closed** 2021-07-17 22:07 UTC
