### ISSUE TITLE
Wrong signature in received PDU on MacOS Big Sur Host

### ISSUE THREAD

**Issue by hgourvest** [sahlberg/libsmb2#226] opened 2022-05-10 12:16 UTC
https://github.com/sahlberg/libsmb2/blob/40550b0cbc4bb3d38800770749fe60e0e9485155/lib/socket.c#L578

I have a signature verification problem with Mac OS Big Sur, it doesn't happen when listing files, only when trying to open a file and read it. I use the Sync API, SMB2_VERSION_ANY2, SMB2_NEGOTIATE_SIGNING_ENABLED, on Android ARM v8.

**Comment by delins** [comment] 2022-08-03 22:36
Are you using libsmb2 from a single thread, or multiple? Also, it's unclear to me which system you've got libsmb2 running on, the Mac or an Android device? If Mac, does it have an M1/M2 chip, or an Intel one?

**Comment by hgourvest** [comment] 2022-08-04 15:18
I can have multiple threads on separate connections. The program that uses the library is an android application that connects to a macOS host. Windows and Linux hosts work fine. I had to comment out the verification code to be able to read the files, no corruption detected.

**Comment by delins** [comment] 2022-08-09 13:28
It's likely the same issue as #230 then; using multiple threads and signing enabled

**Comment by sahlberg** [comment] 2023-01-16 06:20
Close as duplicate of #230

**Closed by sahlberg** 2023-01-16 06:20 UTC
